name: IAC Container App Environment

on: 
    workflow_dispatch:
        inputs:
          containerAppEnvName :
            description: 'Container App Environment Name'     
            required: true
            default: 'cae-'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_RBAC_DEPLOY }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./Main_Deployments/ContainerAppEnvironment.bicep
        parameters: containerAppEnvName=${{github.event.inputs.containerAppEnvName }}
        failOnStdErr: false
