# This is a basic workflow to help you get started with Actions

name: IAC - Azure Compute Gallery
# Controls when the workflow will run
on:

  workflow_dispatch:
    inputs:
        acgName:
          description: 'Compute Gallery Name'     
          required: true
        
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_RBAC_DEPLOY }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./Main_Deployments/AzureComputeGallery.bicep
         parameters: acgName=${{github.event.inputs.acrName}} location='westus3' allowSoftDelete=false

