name: IAC Azure Function

on: 
    workflow_dispatch:
        inputs:
          storageAccountName:
            description: 'Storage Account Name'     
            required: true
            default: 'st'
          functionAppName:
            description: 'Function Name'     
            required: true
            default: 'fn-'
          resourceLocation:
            type: choice
            description: Make a choice
            options:
            - westus2
            - westus2
            
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_RBAC_DEPLOY }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1      
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: 'rg-websocket-apim' #${{ secrets.AZURE_RG }}
        template: ./Main_Deployments/FullFunctionDeployment.bicep
        parameters: Location=${{github.event.inputs.resourceLocation}} StorageAccountName=${{github.event.inputs.storageAccountName}} FunctionAppName=${{github.event.inputs.functionAppName}} SubscriptionId=${{ secrets.AZURE_SUBSCRIPTION}} KeyVaultName=${{ secrets.AZURE_KEYVAULT_NAME}} KeyVaultRGName=${{ secrets.AZURE_KEYVAULT_RG_NAME}}
        failOnStdErr: false
