name: IAC Azure Storage

on: 
    workflow_dispatch:
        inputs:
          storageAccountName:
            description: 'Storage Account Name'     
            required: true
            default: 'st'
         
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_RBAC_DEPLOY }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./Main_Deployments/Storage.bicep
        parameters: StorageAccountName=${{ github.event.inputs.storageAccountName }} KeyVaultName=${{ secrets.AZURE_KEYVAULT_NAME }} SubscriptionId=${{ secrets.AZURE_SUBSCRIPTION_ID }}
        failOnStdErr: false
