# This is a basic workflow to help you get started with Actions

name: IAC - Azure Container Registry
# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
        acrName:
          description: 'Registry Name'     
          required: true
        RGName:
          description: 'Resource Group'     
          required: true
        
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_RBAC_DEPLOY }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ github.event.inputs.RGName }}
        template: ./IaC/acr.bicep
        parameters: acrName=${{github.event.inputs.acrName}}
        failOnStdErr: false
